### ISSUE TITLE
undefined method migrate

### ISSUE THREAD

**Issue by patrickhno** [adacosta/mongoid_rails_migrations#14]
I have a class MigrateHistoriesToMongodb < Mongoid::Migration with the usual up and down functions in db/migrate.

Is this a 3.1 issue of some kind that needs to be resolved, or is it something else?

```
undefined method `migrate' for #<MigrateHistoriesToMongodb:0x000001045c2060>
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:507:in `migrate'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:687:in `block (2 levels) in migrate'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:742:in `call'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:742:in `block in ddl_transaction'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/transactions.rb:208:in `transaction'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:742:in `ddl_transaction'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:686:in `block in migrate'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:671:in `each'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:671:in `migrate'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:549:in `up'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/migration.rb:530:in `migrate'
/Users/patrick/develop/trendmover.com/sqlite3/ruby/1.9.1/gems/activerecord-3.1.0.rc6/lib/active_record/railties/databases.rake:161:in `block (2 levels) in <top (required)>'
/Users/patrick/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
```

**Comment by adacosta** [comment]
@aauthor - I mostly like your idea. My thoughts are that doesn't guarantee the migration state of the mongodb instance in isolation. Also, it could be considered less than ideal tracking the state of one database from another database. Closing for now because this is old.
